### ISSUE TITLE
Python ASIC framework

### ISSUE THREAD

**Issue by UpstreamData** [HashFrontier/Hash-Kit#1]
Hey, just saw this project and figured with it being so early it might benefit from a python asic framework.  I am building one, called [`pyasic`](https://github.com/UpstreamData/pyasic), and it is currently up on pip and supports a whole bunch of miners.  

I also actively work on it and would be happy to add support for miners as needed (for any miners you can get API outputs for that aren't already supported).

Let me know if this is helpful to you or if you need any collaboration on anything.

**Comment by HashFrontier** [comment]
Howdy, thanks for reaching out. That would be a hell of an upgrade. Hash Kit should work with anything that supports the 'stats' endpoint, but it appears that not all currently available miners use the same cgminer API. Will update the readme and take a look at integrating pyasic.

**Comment by UpstreamData** [comment]
Awesome.  Most miners support the `stats` endpoint, but I know of a few that don't provide some of the main data there.

Pyasic provides a class for each type of miner, each of which contains a helper function `get_data` which returns a dataclass, so that should make it easy to standardize.

Basic flow is `get_miner(ip) -> MinerClassInstance.get_data() -> MinerData.hashrate`

**Comment by HashFrontier** [comment]
Tested pyasic against a few scenarios seen IRL and unfortunately it just won't support a few key things that are needed. Will keep an eye on this and potentially contribute some changes.

**Comment by UpstreamData** [comment]
Good to know.  Let me know what issues you are having or if you need any help with them and I can hopefully provide support.

I am hoping to release version 1.0.0 soon, so fixing issues and finalizing the API is the main focus right now.

**Comment by UpstreamData** [comment]
I'm working on a forked version that will run off pyasic, but while doing so I saw this supports Vnish.  Which Vnish version miners have you tested this on, and would you mind sending me some Vnish API outputs for testing with pyasic?  

I have basic support for Vnish already added in the factory, but I'm pretty sure full support isn't implemented or is sketchy at best, so I would love to get that working for ya.
